version: '3'

services:
   postgres:
      image: postgres:latest
      container_name: postgres
      ports:
         - '6500:5432'
      volumes:
         - postgresDB:/var/lib/postgresql/data
      env_file:
         - ./.env

   redis:
      image: redis:latest
      container_name: redis
      ports:
         - '6379:6379'
      volumes:
         - redisDB:/data

volumes:
   postgresDB:
   redisDB:
